CREATE TABLE BOOK(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    magazine_id BIGINT NOT NULL,
    title VARCHAR(1000) NOT NULL,
    author VARCHAR(1000) NOT NULL,
    genre VARCHAR(1000) NOT NULL,
    publicationyear BIGINT NOT NULL,
    amount BIGINT NULL
);

CREATE TABLE LIBRARY(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    magazine_id BIGINT NOT NULL,
    name VARCHAR(1000) NOT NULL,
    street VARCHAR(1000) NOT NULL
);

CREATE TABLE MAGAZINE(
    id BIGINT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE EMPLOYEE(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

);

CREATE TABLE READER(
    id BIGINT AUTO_INCREMENT PRIMARY KEY
);

ALTER TABLE BOOK
    ADD CONSTRAINT book_magazine_id
    FOREIGN KEY (magazine_id) REFERENCES book(id)
;
ALTER TABLE LIBRARY
    ADD CONSTRAINT library_magazine_id
    FOREIGN KEY (magazine_id) REFERENCES library(id)
;